const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, '../../pages');
const outputFile = path.join(__dirname, '../../components/CustomSidebar/generatedPageLinks.js');

function getPageLinks(dir, baseRoute = '') {
  const files = fs.readdirSync(dir);
  const links = [];

  files.forEach(file => {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    const relativePath = path.relative(pagesDir, fullPath);

    if (stat.isDirectory()) {
      links.push(...getPageLinks(fullPath, path.join(baseRoute, file)));
    } else {
      const ext = path.extname(file);
      const name = path.basename(file, ext);

      if (['.js','.jsx', '.tsx', '.mdx'].includes(ext) && name !== 'index') {
        const route = path.join('/', baseRoute, name).replace(/\\/g, '/');
        const label = name.charAt(0).toUpperCase() + name.slice(1); // 簡單處理標題
        links.push({ label, route });
      }

      // 特別處理 index.jsx → 對應路徑是 baseRoute
      if (['.js', '.jsx', '.tsx', '.mdx'].includes(ext) && name === 'index') {
        const route = path.join('/', baseRoute).replace(/\\/g, '/');
        const label = path.basename(baseRoute) || 'Home';
        links.push({ label, route });
      }
    }
  });

  return links;
}

function generateSidebarModule(links) {
  const imports = `// ⚠️ Auto-generated by generateSidebarFromPages.js\n`;
  const exportContent = `export const pageLinks = ${JSON.stringify(links, null, 2)};\n`;

  fs.writeFileSync(outputFile, imports + '\n' + exportContent, 'utf8');
  console.log(`✅ Sidebar links generated in: ${outputFile}`);
}

const links = getPageLinks(pagesDir);
generateSidebarModule(links);
