// ⚠️ Auto-generated by generateSidebarFromPages.js

export const pageLinks = [
  {
    "label": "FormTemplatePage",
    "route": "/FormTemplatePage"
  },
  {
    "label": "Home",
    "route": "/"
  },
  {
    "label": "BootstrapJsxAdvancedTemplatePage",
    "route": "/template/BootstrapJsxAdvancedTemplatePage"
  },
  {
    "label": "BootstrapJsxTemplatePage",
    "route": "/template/BootstrapJsxTemplatePage"
  },
  {
    "label": "FormTemplatePage",
    "route": "/template/form/FormTemplatePage"
  }
];
